# Generated by Django 3.1.1 on 2020-10-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product', '0004_auto_20201027_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subproductcategoriesmodels'),
        ),
    ]
