# Generated by Django 3.1.1 on 2020-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoriesmodels',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
