# Generated by Django 3.1.1 on 2020-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201020_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproductcategoriesmodels',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
