# Generated by Django 3.1.1 on 2020-10-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20201020_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproductcategoriesmodels',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.productcategoriesmodels'),
        ),
    ]
